FROM jenkins/jenkins:lts
ENV CASC_JENKINS_CONFIG="/var/jenkins_home/casc_configs/jenkins.yaml"
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
#COPY id_rsa /usr/share/jenkins/ref/id_rsa
COPY jenkins.yaml ${CASC_JENKINS_CONFIG}
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
#RUN /usr/local/bin/install-plugins.sh configuration-as-code-support workflow-cps-global-lib
#EXPOSE 8085

